apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-a
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: service-a
                  image: $DOCKER_IMAGE
                  env:
                      - name: DATABASE_HOST
                        value: redis
