apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-service-a
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: service-a.127.0.0.1.nip.io
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: service-a
                            port:
                                number: 80
