apiVersion: apps/v1
kind: Deployment
metadata:
    name: service-a
    labels:
        app: service-a
spec:
    replicas: 3
    selector:
        matchLabels:
            app: service-a
    template:
        metadata:
            labels:
                app: service-a
        spec:
            containers:
                - name: service-a
                  ports:
                      - containerPort: 80
                  env:
                      - name: PORT
                        value: '3000'
                      - name: LOG_LEVEL
                        value: log,error,warn,debug
